```{r}
library(MASS)
library(np)
library(ggplot2)
library(ggsci)
```

```{r}
# Load your RData file
load("/Users/yangjinzhe/Desktop/doctorvisits.rda")

# Suppose your object is called 'df' (data.frame)
write.csv(doctorvisits, "doctorvisits.csv", row.names = FALSE)

tail(doctorvisits)
model <- glm(numvisit ~ reform + badh + age + educ + loginc, family = poisson, doctorvisits)

model_nb <- glm.nb(numvisit ~ reform + badh + age + educ + loginc, doctorvisits)

# model result for poisson regression
model
p_res <- residuals(model, type = "pearson")
sum(abs(p_res) > 3)

# model result for negtive binomial regression
model_nb
p_res <- residuals(model_nb, type = "pearson")
sum(abs(p_res) > 3)

theta <- 0.9978731512246424
mu <- 3.742388660271744
dnbinom(0, size = theta, mu = mu)
```

## Global Fit Check
```{r}
y_grid <- seq(min(doctorvisits$numvisit), max(doctorvisits$numvisit), 1)
poisson_mu_hat <- predict(model, type = "response")
poisson_marginal <- rep(NA, length(y_grid))
for (i in 1:length(y_grid)) {
    yi <- y_grid[i]
    poisson_marginal[i] <- mean(dpois(yi, poisson_mu_hat))
}
df_marginal_poisson <- data.frame(x = y_grid, y = poisson_marginal)

df_numvisit <- data.frame(table(doctorvisits$numvisit))
df_emp <- data.frame(x = as.numeric(as.character(df_numvisit$Var1)), y = df_numvisit$Freq / dim(doctorvisits)[1])

head(df_numvisit)

df_hist <- data.frame(
    x = as.numeric(names(table(doctorvisits$numvisit))),
    prob = as.numeric(prop.table(table(doctorvisits$numvisit)))
)

# p <- ggplot(mtcars, aes(wt, mpg, color = factor(cyl))) +
#     # Histogram
#     geom_line(data = df_emp, aes(x = x, y = y, color = "Empirical KDE"), linewidth = 1) +
#     geom_line(
#         data = df_marginal_poisson, aes(x = x, y = y, color = "Analytical Marginal"),
#         linetype = "dashed", linewidth = 1
#     ) +
#     scale_color_manual(values = c(
#         "Empirical KDE" = "black",
#         "Analytical Marginal" = "blue"
#     )) +
#     labs(
#         title = "Empirical vs. Analytical Marginal Distribution",
#         x = "Y",
#         y = "Probability",
#         color = NULL
#     ) +
#     theme_bw() +
#     scale_color_npg() + # Nature Publishing Group style
#     theme(
#         legend.position = "top",
#         panel.grid = element_blank(),
#         axis.text = element_text(color = "grey30"),
#         axis.title = element_text(color = "grey40"),
#         plot.title = element_text(color = "grey10"),
#         legend.text = element_text(color = "grey10"),
#         legend.title = element_text(color = "grey10"),
#         legend.margin = margin(b = -5) # pull legend closer
#     )
p <- ggplot() +

    # Empirical bar chart
    # geom_col(
    #     data = df_hist,
    #     aes(
    #         x = x,
    #         y = prob,
    #         fill = "Empirical Frequency"
    #     ),
    #     alpha = 0.4,
    #     width = 0.9
    # ) +

    # Empirical KDE / smoothed empirical distribution
    geom_line(
        data = df_emp,
        aes(
            x = x,
            y = y,
            color = "Empirical Distribution"
        ),
        linewidth = 1
    ) +

    # Model implied marginal distribution
    geom_line(
        data = df_marginal_poisson,
        aes(
            x = x,
            y = y,
            color = "Analytical Marginal"
        ),
        linetype = "dashed",
        linewidth = 1
    ) +
    scale_color_manual(values = c(
        "Empirical KDE" = "black",
        "Analytical Marginal" = "blue"
    )) +
    scale_fill_manual(values = c(
        "Empirical Frequency" = "grey70"
    )) +
    labs(
        title = "Empirical vs. Analytical Marginal Distribution",
        x = "Y",
        y = "Probability",
        color = NULL,
        fill = NULL
    ) +
    theme_bw() +
    scale_color_npg() +
    theme(
        legend.position = "top",
        panel.grid = element_blank(),
        axis.text = element_text(color = "grey30"),
        axis.title = element_text(color = "grey40"),
        plot.title = element_text(color = "grey10"),
        legend.text = element_text(color = "grey10"),
        legend.title = element_text(color = "grey10"),
        legend.margin = margin(b = -5)
    )

p
ggsave("./figures/global_check_3_poisson_reg.svg", plot = p, width = 6, height = 4)
ggsave("./figures/global_check_3_poisson_reg.pdf", plot = p, width = 6, height = 4)


# negtive binomial
neg_mu_hat <- predict(model_nb, type = "response")
theta_hat <- model_nb$theta
neg_marginal <- rep(NA, length(y_grid))
for (i in 1:length(y_grid)) {
    yi <- y_grid[i]
    neg_marginal[i] <- mean(dnbinom(yi, size = theta_hat, mu = neg_mu_hat))
}
df_marginal_poisson <- data.frame(x = y_grid, y = neg_marginal)

p <- ggplot(mtcars, aes(wt, mpg, color = factor(cyl))) +
    geom_line(data = df_emp, aes(x = x, y = y, color = "Empirical Distribution"), linewidth = 1) +
    geom_line(
        data = df_marginal_poisson, aes(x = x, y = y, color = "Analytical Marginal"),
        linetype = "dashed", linewidth = 1
    ) +
    scale_color_manual(values = c(
        "Empirical Distribution" = "black",
        "Analytical Marginal" = "blue"
    )) +
    labs(
        title = "Empirical vs. Analytical Marginal Distribution",
        x = "Y",
        y = "Probability",
        color = NULL
    ) +
    theme_bw() +
    scale_color_npg() + # Nature Publishing Group style
    theme(
        legend.position = "top",
        panel.grid = element_blank(),
        axis.text = element_text(color = "grey30"),
        axis.title = element_text(color = "grey40"),
        plot.title = element_text(color = "grey10"),
        legend.text = element_text(color = "grey10"),
        legend.title = element_text(color = "grey10"),
        legend.margin = margin(b = -5) # pull legend closer
    )
ggsave("./figures/global_check_3_neg_reg.svg", plot = p, width = 6, height = 4)
ggsave("./figures/global_check_3_neg_reg.pdf", plot = p, width = 6, height = 4)
p
```

```{r}
summary(model_nb)

# bw_cond <- npcdistbw(numvisit ~ factor(reform) + factor(badh) + age + educ + loginc,
#     data = doctorvisits,
#     wmethod = "cv.ml"
# )

# bw_cond
```

```{r}
tail(predict(model_nb), )

c(1, 1, 0, 38, 7, 7.72323894500732) %*% c(-0.407475, -0.137408, 1.131247, 0.005570, -0.005320, 0.137129)
```

```{r}
model
tail(predict(model, type = "response"))
linearCom <- c(1, 1, 0, 38, 7, 7.72323894500732) %*% c(-0.421508, -0.139884, 1.132628, 0.004885, -0.011814, 0.152025)
linearCom
exp(linearCom)
```

```{r}
data_pca <- prcomp(
    data.frame(
        age = doctorvisits[, "age"],
        educ = doctorvisits[, "educ"],
        loginc = doctorvisits[, "loginc"]
    ),
    center = TRUE, scale. = TRUE
)

data_pca
summary(data_pca)
head(data_pca$x)
head(doctorvisits)
```

<!-- Conditional distribution data (2227 observations, 6 variable(s))
(1 dependent variable(s), and 5 explanatory variable(s))

                        numvisit
Dep. Var. Bandwidth(s): 1.257102
                        factor(reform) factor(badh)      age      educ   loginc
Exp. Var. Bandwidth(s):      0.4845307   0.01094098 5.786841 0.4327276 213813.7

Bandwidth Selection Method: Least Squares Cross-Validation
Formula: numvisit ~ factor(reform) + factor(badh) + age + educ + loginc
Bandwidth Type: Fixed
Objective Function Value: 0.1854022 (achieved on multistart 2)

Continuous Kernel Type: Second-Order Gaussian 
No. Continuous Dependent Vars.: 1 
No. Continuous Explanatory Vars.: 3 

Unordered Categorical Kernel Type: Aitchison and Aitken  
No. Unordered Categorical Explanatory Vars.: 2 -->
